/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 18-Oct-2023 17:41:56
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 9
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\MatLab\extern\include\tmwtypes.h 
 */
#define FILTER_LENGTH 9
const double Coeffs[9] = {
    0.01814629764993,  0.04875781071901,   0.1227060405853,   0.1967056507375,
     0.2273684006167,   0.1967056507375,   0.1227060405853,  0.04875781071901,
    0.01814629764993
};
