/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 18-Oct-2023 15:24:57
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 65
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\MatLab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define FILTER_LENGTH 65
const float Coeffs[65] = {
   0.002023161156, 0.002099979203, 0.002291053534, 0.002597837476, 0.003020442324,
    0.00355761731, 0.004206744488, 0.004963851534, 0.005823639687, 0.006779532414,
   0.007823736407,  0.00894731842,  0.01014030166,  0.01139176916,  0.01268998347,
    0.01402251795,  0.01537639555,  0.01673823595,  0.01809441112,  0.01943119988,
    0.02073494904,  0.02199223079,  0.02319000661,   0.0243157763,   0.0253577251,
    0.02630487084,  0.02714718692,  0.02787572518,  0.02848272771,  0.02896171249,
    0.02930755913,  0.02951656096,  0.02958647721,  0.02951656096,  0.02930755913,
    0.02896171249,  0.02848272771,  0.02787572518,  0.02714718692,  0.02630487084,
     0.0253577251,   0.0243157763,  0.02319000661,  0.02199223079,  0.02073494904,
    0.01943119988,  0.01809441112,  0.01673823595,  0.01537639555,  0.01402251795,
    0.01268998347,  0.01139176916,  0.01014030166,  0.00894731842, 0.007823736407,
   0.006779532414, 0.005823639687, 0.004963851534, 0.004206744488,  0.00355761731,
   0.003020442324, 0.002597837476, 0.002291053534, 0.002099979203, 0.002023161156
};
