/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 18-Oct-2023 15:24:23
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 33
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\MatLab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define FILTER_LENGTH 33
const float Coeffs[33] = {
   0.004462942481, 0.004979223479, 0.006474536378, 0.008903468959,  0.01218243409,
    0.01619277894,  0.02078535967,  0.02578639798,  0.03100440092,  0.03623783961,
    0.04128327221,  0.04594358802,  0.05003603548,  0.05339965224,  0.05590185151,
    0.05744385719,  0.05796471983,  0.05744385719,  0.05590185151,  0.05339965224,
    0.05003603548,  0.04594358802,  0.04128327221,  0.03623783961,  0.03100440092,
    0.02578639798,  0.02078535967,  0.01619277894,  0.01218243409, 0.008903468959,
   0.006474536378, 0.004979223479, 0.004462942481
};
