/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 18-Oct-2023 17:43:46
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 17
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\MatLab\extern\include\tmwtypes.h 
 */
#define FILTER_LENGTH  17
const double Coeffs[17] = {
   0.009101971112099,  0.01311510817241,  0.02453299709212,  0.04165114647588,
    0.06187872032795,  0.08213591263646,  0.09932827837317,   0.1108244355673,
     0.1148628604851,   0.1108244355673,  0.09932827837317,  0.08213591263646,
    0.06187872032795,  0.04165114647588,  0.02453299709212,  0.01311510817241,
   0.009101971112099
};
