/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 18-Oct-2023 17:53:56
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 33
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\MatLab\extern\include\tmwtypes.h 
 */
#define FILTER_LENGTH 33
const double Coeffs[33] = {
   0.004462942263946, 0.004979223676832, 0.006474536280547,  0.00890346860581,
      0.012182434349,   0.0161927797426,  0.02078535915636,  0.02578639735828,
      0.031004401422,  0.03623783965609,  0.04128327116619,  0.04594358925232,
    0.05003603572284,  0.05339965168632,  0.05590185314379,  0.05744385580114,
     0.0579647214319,  0.05744385580114,  0.05590185314379,  0.05339965168632,
    0.05003603572284,  0.04594358925232,  0.04128327116619,  0.03623783965609,
      0.031004401422,  0.02578639735828,  0.02078535915636,   0.0161927797426,
      0.012182434349,  0.00890346860581, 0.006474536280547, 0.004979223676832,
   0.004462942263946
};
