/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 18-Oct-2023 15:22:10
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 17
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\MatLab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define FILTER_LENGTH 17
const float Coeffs[17] = {
   0.009101971053,  0.01311510801,  0.02453299798,  0.04165114462,  0.06187872216,
    0.08213591576,   0.0993282795,   0.1108244359,   0.1148628592,   0.1108244359,
     0.0993282795,  0.08213591576,  0.06187872216,  0.04165114462,  0.02453299798,
    0.01311510801, 0.009101971053
};
